#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=8g,walltime=0:05:00
#PBS -N app-tracts-properties
#PBS -V

# Extract fields from config.json

tcks=$(jq -r .tcks config.json)
t1w=$(jq -r .t1 config.json)
t2w=$(jq -r .t2 config.json)
parc=$(jq -r .parc config.json)
mask=$(jq -r .mask config.json)

# Assign the first available field to 'anat'
if [ -n "$t1w" ] && [ "$t1w" != "null" ]; then
    anat=$t1w
elif [ -n "$21w" ] && [ "$t1w" != "null" ]; then
    anat=$t2w
elif [ -n "$parc" ] && [ "$parc" != "null" ]; then
    anat=$parc
elif [ -n "$mask" ] && [ "$mask" != "null" ]; then
    anat=$mask
else
    echo "Error: No valid anatomical reference found in config.json" >&2
    exit 1
fi


for tck in $( ls ${tcks}/*.tck ); do
  
  ##### Dipy analysis
  echo "processing track" ${tck} "..."
  trk=./trk/$( basename ${tck//'.tck'/'.trk'} )

  mkdir ./dipy_stat
  dipy_stat=./dipy_stat/$( basename ${trk//'.trk'/''} ).tsv

  singularity exec -e docker://brainlife/dipy:1.4.1 bash ./scripts/dipy_analysis.sh ${tck} ${anat} ${dipy_stat}

  cat ${dipy_stat}

  

  ##### DSI analysis
  mkdir -p ./dsi_stat
  dsi_stat=./dsi_stat/$( basename ${trk//'.trk'/''} ).tsv
  
  singularity exec --nv -e docker://dsistudio/dsistudio:hou-2024-12-26 bash ./scripts/dsi_analysis.sh ${trk} ${dsi_stat}

  cat ${dsi_stat}

  ##### merging results

  mkdir ./stat
  stat_track=./stat/$( basename ${trk//'.trk'/''} ).tsv

  singularity exec -e docker://brainlife/dipy:1.4.1 python ./scripts/vstack_tsv.py ${dsi_stat} ${dipy_stat} ${stat_track} 


  cat ${stat_track}

done

##### Merge tractmeasure files in one

singularity exec -e docker://brainlife/dipy:1.4.1 python ./scripts/merge_tractmeasures.py ./stat ./stat/tractmeasures.tsv
echo "Output file stored as: "stat/tractmeasures.tsv
