#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=8g,walltime=0:05:00
#PBS -N app-tracts-properties
#PBS -V

# Extract fields from config.json

tcks=$(jq -r .tcks config.json)
t1w=$(jq -r .t1 config.json)
t2w=$(jq -r .t2 config.json)
parc=$(jq -r .parc config.json)
mask=$(jq -r .mask config.json)

# Assign the first available field to 'anat'
if [ -n "$t1w" ] && [ "$t1w" != "null" ]; then
    anat=$t1w
elif [ -n "$21w" ] && [ "$t1w" != "null" ]; then
    anat=$t2w
elif [ -n "$parc" ] && [ "$parc" != "null" ]; then
    anat=$parc
elif [ -n "$mask" ] && [ "$mask" != "null" ]; then
    anat=$mask
else
    echo "Error: No valid anatomical reference found in config.json" >&2
    exit 1
fi


for tck in $( ls ${tcks}/*.tck ); do
  
  ##### Convert tck to trk

  echo "processing track" ${tck} "..."

  singularity exec -e docker://brainlife/dipy:1.4.1 python ./tck2trk.py ${anat} ${tck}
  mkdir trk
  cp ${tck//'.tck'/'.trk'} ./trk

  trk=./trk/$( basename ${tck//'.tck'/'.trk'} )

  ##### Convert trk to tt

  gzip -c ${trk} > data.${trk##*/}.gz

  singularity exec -e docker://dsistudio/dsistudio dsi_studio --action=exp --source=data.${trk##*/}.gz --output=data.${trk##*/}.tt.gz

  rm -f data.${trk##*/}.gz

  # move file to tt folder
  mkdir -p tt
  tt=tt/$( basename ${trk//'.trk'/''} ).tt.gz
  mv data.${trk##*/}.tt.gz ${tt}

  ##### analyze tt file

  echo "Starting DSI Studio analysis..."
  singularity exec --nv -e docker://dsistudio/dsistudio:hou-2024-12-26 dsi_studio --action=ana --source="${tt}" --tract="${tt}" --export=stat

  # Move file to stat folder
  mkdir -p stat
  if [[ -f "${tt}.stat.txt" ]]; then
    mv "${tt}.stat.txt" stat/tractmeasure.tsv
  else
    echo "ERROR: Output file not generated. Check DSI Studio logs."
    exit 1
  fi

  stat_track=stat/$( basename ${tck//'.tck'/''} ).tsv
  mv stat/tractmeasure.tsv ${stat_track}

  echo "DSI Studio analysis completed successfully!"

  echo 'Calculate curvature and torsion using dipy...'
  
  singularity exec -e docker://brainlife/dipy:1.4.1 python ./scripts/compute_curv_n_tors.py ${trk} --save-stats stat/curv_tors.tsv


  singularity exec -e docker://brainlife/dipy:1.4.1 python ./scripts/horizontal_stack_tsv.py ${stat_track} stat/curv_tors.tsv ${stat_track}

  rm stat/curv_tors.tsv

  cat stat/tractmeasure.tsv

done

##### Merge tractmeasure files in one

singularity exec -e docker://brainlife/dipy:1.4.1 python ./scripts/merge_tractmeasures.py ./stat ./stat/tractmeasures.tsv
echo "Output file stored as: "stat/tractmeasures.tsv
